version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: local-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    # Optional: Add environment variables for username and password
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: myuser
    #   MONGO_INITDB_ROOT_PASSWORD: mypassword

volumes:
  mongo-data:
